### ISSUE TITLE
The osm_to_sandbox command does not become available after `pip install --user osm-to-sandbox`

### ISSUE THREAD

**Issue by deevroman** [Zverik/osm_to_sandbox#6]
Tested on 
- macOS 14.0
- ubuntu 22.04
- Debian GNU/Linux 12 (`python`, Docker image)

It seems that either some other condition is required (e.g. setting the env vars), or `pip install --user osm-to-sandbox` doesn't work completely. (the package is installed in `site-packages`)

The same problem was in version 1.0 as well

**Comment by Zverik** [comment]
Please check for version 1.1. I installed it into a virtual environment, and the command is there. In 1.0 there was a typo in the config file.

**Comment by deevroman** [comment]
Yes, in venv and on macos it worked. On ubuntu I now see a warning that /home/user/.local/bin should be added to the PATH. Thanks
